import Navbar from '@/components/shared/Navbar'
import './globals.css'
import Footer from '@/components/shared/Footer'
import { Toaster } from '@/components/ui/toaster'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="w-full min-h-screen flex flex-col">
        <Navbar />
        {children}
        <Footer />
        <Toaster />
      </body>
    </html>
  )
}
